"""
ncaa_submission_2026.certification.certifier
=============================================
Stage 09 — Orchestrates all certification checks and produces
machine-readable (JSON) and human-readable (Markdown) reports.

Usage
-----
::

    certifier = PrivacyCertifier()
    report = certifier.certify(
        train_df=train_df,
        model=fitted_model,
        X1_val=X1_val,
        X2_val=X2_val,
        y_val=y_val,
    )
    certifier.save_json("certification/privacy_cert.json")
    certifier.save_md("certification/privacy_cert.md")
"""

from __future__ import annotations

import datetime
import json
import logging
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np
import pandas as pd

from ncaa_submission_2026.certification.leakage_detector import DataLeakageDetector, LeakageReport
from ncaa_submission_2026.certification.determinism_checker import DeterminismChecker, DeterminismReport
from ncaa_submission_2026.certification.network_isolator import NetworkIsolator, NetworkIsolationReport
from ncaa_submission_2026.certification.dependency_auditor import DependencyAuditor, DependencyAuditReport

logger = logging.getLogger(__name__)


@dataclass
class CertificationReport:
    """
    Full privacy and reproducibility certification report.

    Attributes
    ----------
    passed : bool
        True only if ALL checks passed.
    timestamp : str
    leakage : LeakageReport
    determinism : DeterminismReport
    network_isolation : NetworkIsolationReport
    dependency_audit : DependencyAuditReport
    summary : str
    """

    passed: bool
    timestamp: str
    leakage: LeakageReport
    determinism: DeterminismReport
    network_isolation: NetworkIsolationReport
    dependency_audit: DependencyAuditReport
    summary: str
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "passed": self.passed,
            "timestamp": self.timestamp,
            "summary": self.summary,
            "metadata": self.metadata,
            "checks": {
                "leakage": self.leakage.to_dict(),
                "determinism": self.determinism.to_dict(),
                "network_isolation": self.network_isolation.to_dict(),
                "dependency_audit": self.dependency_audit.to_dict(),
            },
        }

    def to_markdown(self) -> str:
        """Generate a human-readable Markdown certification report."""
        status = "✅ PASSED" if self.passed else "❌ FAILED"
        lines = [
            f"# NCAA 2026 Prediction System — Privacy Certification",
            f"",
            f"**Status:** {status}",
            f"**Timestamp:** {self.timestamp}",
            f"",
            f"## Summary",
            f"",
            self.summary,
            f"",
            f"## 1. Data Leakage Detection",
            f"",
            f"- **Result:** {'CLEAN' if not self.leakage.leakage_found else 'LEAKAGE DETECTED'}",
            f"- **Details:** {self.leakage.details}",
            f"",
            f"## 2. Deterministic Inference",
            f"",
            f"- **Result:** {'DETERMINISTIC' if self.determinism.is_deterministic else 'NON-DETERMINISTIC'}",
            f"- **Runs:** {self.determinism.n_runs}",
            f"- **Mismatches:** {self.determinism.n_mismatches}",
            f"- **Details:** {self.determinism.details}",
            f"",
            f"## 3. Network Isolation",
            f"",
            f"- **Result:** {'ISOLATED' if self.network_isolation.is_isolated else 'NOT ISOLATED'}",
            f"- **Network calls attempted:** {self.network_isolation.network_calls_attempted}",
            f"- **Details:** {self.network_isolation.details}",
            f"",
            f"## 4. Dependency Audit",
            f"",
            f"- **Result:** {'PASSED' if self.dependency_audit.audit_passed else 'FAILED'}",
            f"- **Python version:** {self.dependency_audit.python_version.split()[0]}",
            f"- **Packages installed:** {len(self.dependency_audit.packages)}",
            f"- **Missing required:** {self.dependency_audit.missing_required or 'None'}",
            f"- **Details:** {self.dependency_audit.details}",
            f"",
            f"---",
            f"*Generated by FieldSense-AI certification pipeline (Stage 09/10)*",
        ]
        return "\n".join(lines)


class PrivacyCertifier:
    """
    Runs all certification checks and produces a CertificationReport.

    Parameters
    ----------
    test_season : int
        The holdout season (2026).
    seed : int
        Random seed used for determinism checks.
    """

    def __init__(self, test_season: int = 2026, seed: int = 42) -> None:
        self.test_season = test_season
        self.seed = seed
        self._report: Optional[CertificationReport] = None

    def certify(
        self,
        train_df: pd.DataFrame,
        model,
        X1_val: np.ndarray,
        X2_val: np.ndarray,
        y_val: Optional[np.ndarray] = None,
        extra_dataframes: Optional[Dict[str, pd.DataFrame]] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> CertificationReport:
        """
        Run all four certification checks.

        Parameters
        ----------
        train_df : pd.DataFrame
            Training DataFrame (should NOT contain season 2026 rows).
        model : MatchupPredictor
        X1_val, X2_val : np.ndarray
            Validation feature arrays.
        y_val : np.ndarray, optional
            Ground-truth labels (not used for checks; stored for metadata).
        extra_dataframes : dict, optional
            Additional named DataFrames to include in the leakage scan.
        metadata : dict, optional
            Extra metadata stored in the report.

        Returns
        -------
        CertificationReport
        """
        ts = datetime.datetime.utcnow().isoformat()

        # 1. Data leakage
        det = DataLeakageDetector(test_season=self.test_season)
        dfs_to_check = {"train_df": train_df}
        if extra_dataframes:
            dfs_to_check.update(extra_dataframes)
        leakage_reports = det.check_many(dfs_to_check)
        # Aggregate: if any has leakage, report the first one with leakage
        combined_leakage = next(
            (r for r in leakage_reports if r.leakage_found),
            leakage_reports[0],
        )

        # 2. Determinism
        checker = DeterminismChecker(seed=self.seed, n_runs=3)
        det_report = checker.check_model(model, X1_val, X2_val)

        # 3. Network isolation
        isolator = NetworkIsolator()
        net_report = isolator.run_isolated(model.predict_proba, X1_val, X2_val)

        # 4. Dependency audit
        auditor = DependencyAuditor()
        dep_report = auditor.audit()

        # Overall pass/fail
        passed = (
            not combined_leakage.leakage_found
            and det_report.is_deterministic
            and net_report.is_isolated
            and dep_report.audit_passed
        )

        checks_summary = []
        checks_summary.append(
            f"Data leakage: {'CLEAN' if not combined_leakage.leakage_found else 'FAILED'}"
        )
        checks_summary.append(
            f"Determinism: {'PASS' if det_report.is_deterministic else 'FAIL'}"
        )
        checks_summary.append(
            f"Network isolation: {'PASS' if net_report.is_isolated else 'FAIL'}"
        )
        checks_summary.append(
            f"Dependency audit: {'PASS' if dep_report.audit_passed else 'FAIL'}"
        )
        summary = (
            f"Overall: {'ALL CHECKS PASSED' if passed else 'ONE OR MORE CHECKS FAILED'}. "
            + " | ".join(checks_summary)
        )

        report = CertificationReport(
            passed=passed,
            timestamp=ts,
            leakage=combined_leakage,
            determinism=det_report,
            network_isolation=net_report,
            dependency_audit=dep_report,
            summary=summary,
            metadata=dict(metadata or {}),
        )
        self._report = report
        logger.info("Certification complete: passed=%s", passed)
        return report

    def save_json(self, path: str) -> None:
        """Write the last certification report to a JSON file."""
        if self._report is None:
            raise RuntimeError("No report available; call certify() first.")
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        with open(p, "w") as f:
            json.dump(self._report.to_dict(), f, indent=2)
        logger.info("Certification JSON written to %s", path)

    def save_md(self, path: str) -> None:
        """Write the last certification report to a Markdown file."""
        if self._report is None:
            raise RuntimeError("No report available; call certify() first.")
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        with open(p, "w") as f:
            f.write(self._report.to_markdown())
        logger.info("Certification Markdown written to %s", path)
