"""
ncaa_models.upset_detector
==========================
Stage 05 — Upset plausibility classification for NCAA matchups.

classify_matchup()
------------------
Takes a base win probability and a list of counterfactual scenarios, and
returns one of:

    "blowout_likely"   Even best-case underdog scenarios give < 0.20 win prob.
    "competitive"      Base probability is 0.35–0.65 (already a close game).
    "upset_plausible"  Favorable counterfactuals push underdog above 0.35 win
                       prob, despite a low base probability.

Priority order:
    1. blowout_likely   (checked first — overrides everything)
    2. competitive      (base_prob in [0.35, 0.65])
    3. upset_plausible  (best valid scenario ≥ 0.35 for underdog)
    4. competitive      (fallback for mid-range games)

UpsetDetector
-------------
Composes a CounterfactualGenerator with a CVSComputer to provide a single
``analyze()`` entry point that returns classification + scenario details.

Detection target
----------------
On historical 11-over-6 and 12-over-5 seed matchups, the detector should
classify ≥ 60% of actual upsets as "upset_plausible" (or "competitive"),
capturing games where the underdog had a realistic path to victory.

Usage
-----
::

    detector = UpsetDetector(model=model, training_dist=dist)
    result = detector.analyze(X1_seed6, X2_seed1)
    print(result["classification"])   # "upset_plausible"
    print(result["best_underdog_prob"])
"""

from __future__ import annotations

import logging
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np

from .counterfactual import (
    CounterfactualGenerator,
    CounterfactualScenario,
    ALL_PERTURBATION_TYPES,
    DEFAULT_CVS_THRESHOLD,
    DEFAULT_SEVERITIES,
)
from .cvs import CVSComputer, TrainingDistribution

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Classification thresholds
# ---------------------------------------------------------------------------

#: Competitive game threshold: base_prob in [LO, HI] → "competitive"
COMPETITIVE_LO: float = 0.35
COMPETITIVE_HI: float = 0.65

#: Blowout threshold: best-case underdog prob below this → "blowout_likely"
BLOWOUT_THRESHOLD: float = 0.20

#: Upset threshold: best-case underdog prob above this → "upset_plausible"
UPSET_THRESHOLD: float = 0.35

BLOWOUT_LIKELY = "blowout_likely"
COMPETITIVE    = "competitive"
UPSET_PLAUSIBLE = "upset_plausible"


# ---------------------------------------------------------------------------
# classify_matchup — standalone function
# ---------------------------------------------------------------------------

def classify_matchup(
    base_prob: float,
    counterfactual_results: Sequence[CounterfactualScenario],
    cvs_threshold: float = DEFAULT_CVS_THRESHOLD,
) -> str:
    """
    Classify a matchup as blowout, competitive, or upset-plausible.

    Parameters
    ----------
    base_prob : float
        Model P(team1 wins) before any perturbation.
    counterfactual_results : list of CounterfactualScenario
        Scenarios generated by :class:`CounterfactualGenerator`.
    cvs_threshold : float
        Minimum CVS for a scenario to be considered.  Default 0.92.

    Returns
    -------
    str
        ``'blowout_likely'`` | ``'competitive'`` | ``'upset_plausible'``

    Logic
    -----
    1. Determine which team is the underdog (lower base probability).
    2. For each valid scenario (cvs ≥ threshold), compute the underdog's
       implied win probability.
    3. If ``max(underdog_probs) < 0.20`` → blowout.
    4. Elif ``0.35 ≤ base_prob ≤ 0.65`` → competitive.
    5. Elif ``max(underdog_probs) ≥ 0.35`` → upset_plausible.
    6. Else → competitive (fallback).
    """
    valid_scenarios = [
        s for s in counterfactual_results if s.cvs >= cvs_threshold
    ]

    # Underdog win probabilities from valid scenarios
    underdog_probs: List[float] = []

    for s in valid_scenarios:
        # Compute underdog win probability for this scenario
        # Underdog = team with lower base probability
        if base_prob >= 0.5:
            # team1 is favourite → team2 is underdog
            # Scenarios that HELP team2: team2 perturbed positively, or team1 hurt
            if s.team == "team2" and s.delta_prob < 0:
                # team2 perturbed, team1 prob dropped → team2 benefits
                underdog_probs.append(1.0 - s.prob)
            elif s.team == "team1" and s.delta_prob < 0:
                # team1 hurt → underdog benefits
                underdog_probs.append(1.0 - s.prob)
            else:
                underdog_probs.append(1.0 - s.prob)
        else:
            # team1 is underdog
            if s.team == "team1" and s.delta_prob > 0:
                # team1 improved → underdog benefits
                underdog_probs.append(s.prob)
            elif s.team == "team2" and s.delta_prob < 0:
                # team2 hurt → underdog benefits
                underdog_probs.append(s.prob)
            else:
                underdog_probs.append(s.prob)

    # Fallback underdog prob = base prob of underdog
    underdog_base_prob = base_prob if base_prob < 0.5 else (1.0 - base_prob)
    if not underdog_probs:
        underdog_probs = [underdog_base_prob]

    best_underdog = max(underdog_probs)

    # Priority: blowout → competitive → upset_plausible → competitive (fallback)
    if best_underdog < BLOWOUT_THRESHOLD:
        return BLOWOUT_LIKELY

    if COMPETITIVE_LO <= base_prob <= COMPETITIVE_HI:
        return COMPETITIVE

    if best_underdog >= UPSET_THRESHOLD:
        return UPSET_PLAUSIBLE

    return COMPETITIVE


# ---------------------------------------------------------------------------
# UpsetDetector — full analysis pipeline
# ---------------------------------------------------------------------------

class UpsetDetector:
    """
    End-to-end upset-plausibility analysis for a matchup.

    Combines counterfactual generation + CVS filtering + classification.

    Parameters
    ----------
    model : MatchupPredictor or callable
        The prediction model (``predict_proba`` or callable).
    training_dist : TrainingDistribution, optional
        Feature distribution for CVS computation.  Uses D1 defaults if None.
    feature_cols : list of str, optional
        Defaults to :data:`~ncaa_models.baseline.FEATURE_COLS`.
    severities : tuple of float
        Severity levels to sample.  Default ``(0.25, 0.50, 0.75)``.
    cvs_threshold : float
        Minimum CVS for validity.  Default 0.92.
    seed : int
        Default random seed for scenario generation.
    """

    def __init__(
        self,
        model,
        training_dist: Optional[TrainingDistribution] = None,
        feature_cols: Optional[List[str]] = None,
        severities: Tuple[float, ...] = DEFAULT_SEVERITIES,
        cvs_threshold: float = DEFAULT_CVS_THRESHOLD,
        seed: int = 42,
    ) -> None:
        from .baseline import FEATURE_COLS as _FC
        fc = list(feature_cols or _FC)

        self.cvs_computer = CVSComputer(
            training_dist=training_dist,
            threshold=cvs_threshold,
            feature_cols=fc,
        )
        self.generator = CounterfactualGenerator(
            model=model,
            feature_cols=fc,
            cvs_computer=self.cvs_computer,
            severities=severities,
            cvs_threshold=cvs_threshold,
        )
        self.cvs_threshold = cvs_threshold
        self.default_seed = seed

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def analyze(
        self,
        X1: np.ndarray,
        X2: np.ndarray,
        seed: Optional[int] = None,
    ) -> Dict:
        """
        Full analysis for a single matchup.

        Parameters
        ----------
        X1, X2 : np.ndarray, shape (feature_dim,)
        seed : int, optional

        Returns
        -------
        dict with keys:
            classification   : str — one of the three labels
            base_prob        : float
            scenarios        : list[CounterfactualScenario]
            valid_scenarios  : list[CounterfactualScenario]
            best_underdog_prob : float
            n_valid          : int
        """
        if seed is None:
            seed = self.default_seed

        scenarios = self.generator.generate(X1, X2, seed=seed)
        base_prob = scenarios[0].base_prob if scenarios else float(
            self.generator._predict(
                np.asarray(X1).reshape(1, -1),
                np.asarray(X2).reshape(1, -1),
            )[0]
        )

        valid = [s for s in scenarios if s.is_valid]
        classification = classify_matchup(base_prob, scenarios, self.cvs_threshold)

        underdog_base = base_prob if base_prob < 0.5 else (1.0 - base_prob)
        best_udp = underdog_base
        if valid:
            if base_prob >= 0.5:
                best_udp = max(1.0 - s.prob for s in valid)
            else:
                best_udp = max(s.prob for s in valid)

        return {
            "classification": classification,
            "base_prob": base_prob,
            "scenarios": scenarios,
            "valid_scenarios": valid,
            "best_underdog_prob": best_udp,
            "n_valid": len(valid),
        }

    def batch_analyze(
        self,
        X1_arr: np.ndarray,
        X2_arr: np.ndarray,
        seed: int = 42,
    ) -> List[Dict]:
        """
        Run analysis for each matchup in a batch.

        Parameters
        ----------
        X1_arr, X2_arr : np.ndarray, shape (n_matchups, feature_dim)
        seed : int
            Each matchup uses ``seed + i`` for reproducibility.

        Returns
        -------
        list of dict
        """
        results = []
        for i, (x1, x2) in enumerate(zip(X1_arr, X2_arr)):
            results.append(self.analyze(x1, x2, seed=seed + i))
        return results

    def detection_rate(
        self,
        X1_arr: np.ndarray,
        X2_arr: np.ndarray,
        is_upset: np.ndarray,
        seed: int = 42,
    ) -> float:
        """
        Fraction of actual upsets classified as ``'upset_plausible'``.

        Parameters
        ----------
        X1_arr, X2_arr : np.ndarray, shape (n, feature_dim)
        is_upset : np.ndarray of bool, shape (n,)
            True where the historical outcome was an upset.
        seed : int

        Returns
        -------
        float in [0, 1]
        """
        results = self.batch_analyze(X1_arr, X2_arr, seed=seed)
        upset_indices = np.where(is_upset)[0]
        if len(upset_indices) == 0:
            return 0.0
        n_detected = sum(
            1 for i in upset_indices
            if results[i]["classification"] == UPSET_PLAUSIBLE
        )
        return n_detected / len(upset_indices)

    def adjusted_probabilities(
        self,
        X1_arr: np.ndarray,
        X2_arr: np.ndarray,
        blend_weight: float = 0.20,
        seed: int = 42,
    ) -> np.ndarray:
        """
        Compute counterfactual-adjusted P(team1 wins) for each matchup.

        Parameters
        ----------
        X1_arr, X2_arr : np.ndarray, shape (n, feature_dim)
        blend_weight : float
        seed : int

        Returns
        -------
        np.ndarray, shape (n,), values in [0, 1]
        """
        probs = []
        for i, (x1, x2) in enumerate(zip(X1_arr, X2_arr)):
            p = self.generator.adjusted_probability(
                x1, x2, seed=seed + i, blend_weight=blend_weight
            )
            probs.append(p)
        return np.array(probs)
